Update laravel.yml

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -53,15 +53,19 @@ jobs:
       - name: Run Laravel Server
         run: php artisan serve --no-reload &
         
-      - name: PHPUnit
-        run: ./vendor/bin/phpunit --do-not-cache-result --testdox-html phpunit.html tests #--filter=LoginTest tests
-      - name: Upload PHPUnit results
-        uses: actions/upload-artifact@v3
-        with:
-          name: phpunit
-          path: phpunit.html
+#       - name: PHPUnit
+#         run: ./vendor/bin/phpunit --do-not-cache-result --testdox-html phpunit.html tests #--filter=LoginTest tests
+#       - name: Upload PHPUnit results
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: phpunit
+#           path: phpunit.html
       - name: Install PHPStan
         run: composer require --dev phpstan/phpstan
+      - name: Check PHP version
+        run: php --version
+#       - name: Install PHP Ext
+#         run: sudo apt-get install -y php7.4-pdo-mysql
       - name: PHPStan
         uses: php-actions/phpstan@v3
         with:
@@ -81,39 +85,39 @@ jobs:
           name: phpstan
           path: phpstan.json
 
-#       - name: List down directory
-#         run: ls
-      - name: Run Dusk Tests
-        run: sudo php artisan dusk:chrome #--filter LoginTest 
-#       - name: Check file exists
-#         run: test -e ./tests/Browser/source/Src_001.txt && echo file exists || echo file not found
-#       - name: Page source
-#         run: cat ./tests/Browser/source/Src_001.txt
+# #       - name: List down directory
+# #         run: ls
+#       - name: Run Dusk Tests
+#         run: sudo php artisan dusk:chrome #--filter LoginTest 
+# #       - name: Check file exists
+# #         run: test -e ./tests/Browser/source/Src_001.txt && echo file exists || echo file not found
+# #       - name: Page source
+# #         run: cat ./tests/Browser/source/Src_001.txt
 
-      - name: Upload Screenshots
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: screenshots
-          path: tests/Browser/screenshots
-      - name: Upload Console Logs
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: console
-          path: tests/Browser/console
-#       - name: Check PHPUnit file exists
-#         run: test -e ./vendor/bin/phpunit && echo file exists || echo file not found
-      - name: Clear cache
-        run: php artisan cache:clear
-      - name: Artisan test
-        run: php artisan test > pa_test.html
-      - name: Upload Artisan Test
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: artisan
-          path: pa_test.html
+#       - name: Upload Screenshots
+#         #if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: screenshots
+#           path: tests/Browser/screenshots
+#       - name: Upload Console Logs
+#         #if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: console
+#           path: tests/Browser/console
+# #       - name: Check PHPUnit file exists
+# #         run: test -e ./vendor/bin/phpunit && echo file exists || echo file not found
+#       - name: Clear cache
+#         run: php artisan cache:clear
+#       - name: Artisan test
+#         run: php artisan test > pa_test.html
+#       - name: Upload Artisan Test
+#         #if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: artisan
+#           path: pa_test.html
         
         
         
@@ -122,66 +126,66 @@ jobs:
         
         
           
-      # BASIC API SCAN
-      - name: ZAP API Scan
-        uses: zaproxy/action-api-scan@v0.1.1
-        with:
-          target: |
-            http://127.0.0.1:8000
-#            https://minxpay.vercel.app/#/sign-in
-#       - name: Create reports directory
-#         run: mkdir reports
-#       - name: List down directory
-#         run: ls
-#       - name: Rename ZAP API Report
-#         run: mv zap_scan.zip reports/zap_scan_api.zip
-#       - name: List down directory
-#         run: ls
-      - name: Upload ZAP API Report - HTML
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: zap_api_html
-          path: report_html.html #reports/zap_scan_api.zip
-      - name: Upload ZAP API Report - MD
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: zap_api_md
-          path: report_md.md
-#       - name: Upload ZAP API Report2
+#       # BASIC API SCAN
+#       - name: ZAP API Scan
+#         uses: zaproxy/action-api-scan@v0.1.1
+#         with:
+#           target: |
+#             http://127.0.0.1:8000
+# #            https://minxpay.vercel.app/#/sign-in
+# #       - name: Create reports directory
+# #         run: mkdir reports
+# #       - name: List down directory
+# #         run: ls
+# #       - name: Rename ZAP API Report
+# #         run: mv zap_scan.zip reports/zap_scan_api.zip
+# #       - name: List down directory
+# #         run: ls
+#       - name: Upload ZAP API Report - HTML
 #         #if: failure()
 #         uses: actions/upload-artifact@v3
 #         with:
-#           name: zap_api2
-#           path: report_html.html
+#           name: zap_api_html
+#           path: report_html.html #reports/zap_scan_api.zip
+#       - name: Upload ZAP API Report - MD
+#         #if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: zap_api_md
+#           path: report_md.md
+# #       - name: Upload ZAP API Report2
+# #         #if: failure()
+# #         uses: actions/upload-artifact@v3
+# #         with:
+# #           name: zap_api2
+# #           path: report_html.html
         
-      # BASIC FULL SCAN
-      - name: ZAP Full Scan
-        uses: zaproxy/action-full-scan@v0.4.0
-        with:
-          target: |
-            http://127.0.0.1:8000
-#            https://minxpay.vercel.app/#/sign-in
+#       # BASIC FULL SCAN
+#       - name: ZAP Full Scan
+#         uses: zaproxy/action-full-scan@v0.4.0
+#         with:
+#           target: |
+#             http://127.0.0.1:8000
+# #            https://minxpay.vercel.app/#/sign-in
             
-#       - name: List down directory
-#         run: ls
-#       - name: Rename ZAP Full Report
-#         run: mv zap_scan.zip reports/zap_scan_full.zip
-#       - name: List down directory
-#         run: ls
-      - name: Upload ZAP Full Report - HTML
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: zap_full_html
-          path: report_html.html #reports/zap_scan_api.zip
-      - name: Upload ZAP Full Report -MD
-        #if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: zap_full_md
-          path: report_md.md
+# #       - name: List down directory
+# #         run: ls
+# #       - name: Rename ZAP Full Report
+# #         run: mv zap_scan.zip reports/zap_scan_full.zip
+# #       - name: List down directory
+# #         run: ls
+#       - name: Upload ZAP Full Report - HTML
+#         #if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: zap_full_html
+#           path: report_html.html #reports/zap_scan_api.zip
+#       - name: Upload ZAP Full Report -MD
+#         #if: failure()
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: zap_full_md
+#           path: report_md.md
         
   
   
